### ISSUE TITLE
Adding support for Media Query Extensions

### ISSUE THREAD

**Issue by pixelastic** [tachyons-css/tachyons-border-colors#5]
Hello,

It does not seem currently possible to change the border color based on the current viewport size. I would like to use the text color on small screens (when displaying items one below the other), while using a default gray color on bigger screen (when displaying them in a grid).

Would it be possible to add the `-ns`, `-m`, `-l` modifiers like in the other modules?

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one.
